### ISSUE TITLE
Implement HomeScreen UI

### ISSUE THREAD

**Issue by nasseryazgi** [nasseryazgi/Betweener#1]
**Tasks**

- [x] Create a reusable components to for item card 
- [x] Implement navigation buttons or menus to other sections or screens of the application
- [x] Ensure responsiveness and adaptability for different screen sizes
**Additional Considerations:**

-Follow our branding guidelines for colors, typography, and overall visual style.

**Comment by Alibaraa** [comment]
everything is done
