### ISSUE TITLE
Implement Profile Screen UI

### ISSUE THREAD

**Issue by nasseryazgi** [nasseryazgi/Betweener#2]
**Tasks**

- [x] Create a reusable components to for links  
- [x] Implement navigation buttons or menus to other sections or screens of the application
- [x] Ensure responsiveness and adaptability for different screen sizes
- [x] Ensure that scrollable sections display icons for actions like delete and edit

**Additional Considerations:**
-Follow our branding guidelines for colors, typography, and overall visual style.
